### ISSUE TITLE
Extension breaks menus and pop-ups when inactive

### ISSUE THREAD

**Issue by minecreeper313** [sergeio/yt-no-spoilers#1]
To start off, I love this extension. It's simple and quick.
But I noticed one issue.

When the extension is enabled in the extensions settings, but it's not activated to hide everything, certain menus and pop-ups break, only showing up for a second before disappearing.

An example of the items affected are: the floating notification box, the create video menu, the floating account menu, the share pop-up, the save video pop-up, the 3 dots menu, the settings gear in the video player, the sort by menu... possibly more.
All of the mentioned items are located in the video page, not on pages like homescreen or search results. The issue seems to only arise on the video page (which would make sense since the extension is designated to hide things there).

I don't know if you're still working on this extension, but I hope you consider finding a solution for this.
Unfortunately I haven't found a replacement extension, and honestly I really enjoy the simplicity that this one provides.
The breaking of the menus is unbearable though. It's probably due to the new UI updates Youtube has made.

**Comment by sergeio** [comment]
Thanks for flagging this! : )

The issue should be fixed in version 1.8.1.  It's live on addons.mozilla.org now.

**Comment by minecreeper313** [comment]
Wow, that was incredibly quick!
I can confirm it's fixed. Thank you so much!!
