### ISSUE TITLE
Hide progress bar in Picture in Picture mode

### ISSUE THREAD

**Issue by ERivierePEReN** [sergeio/yt-no-spoilers#2]
Thank you for your work on this plugin! It's a really nice one.

I wondered if it would be possible to hide the progress bar while using PiP? Not sure if that helps but the option inside about:config for that is `media.videocontrols.picture-in-picture.improved-video-controls.enabled`

**Comment by sergeio** [comment]
I'm glad you like the addon!

I looked into this, and it looks like addons can't edit Firefox's about:config settings for security reasons: https://stackoverflow.com/a/50024435

If you find out otherwise, or (even better) get a working prototype, feel free to reopen or submit a pull request.

**Comment by ERivierePEReN** [comment]
Well good news and bad news!

There is a web api that allows control of the PiP and it in fact works quite well on Chrome based OSes ( this example even hides the control https://googlechrome.github.io/samples/picture-in-picture/css-pseudo-class ). 

But Firefox does not support that api. https://developer.mozilla.org/en-US/docs/Web/API/Picture-in-Picture_API#browser_compatibility ).

**Comment by sergeio** [comment]
Ah bummer.  Well, if Firefox ever supports that API, we can fix this.
